version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql
    container_name: local-sample-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres_data:/bitnami/postgresql
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: local-sample-zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka:latest
    container_name: local-sample-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: OUTSIDE://kafka:9092,INSIDE://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://localhost:9092,INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT,INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: sample-topic:1:1:compact

volumes:
  dataA1:
  dataA2:
  dataA3:
  dataA4:
  postgres_data:
    driver: local

networks:
  default:
    name: my-network
